Repository python-discord/bot, pull requests merged in 2019-12, with the labels that each got.

#675 Allow snekbox in esoteric-python channel
  bot/cogs/snekbox.py
  bot/constants.py
  bot/decorators.py
  config-default.yml
Labels: area: utility, type: enhancement

#672 Enhance timedelta for infraction expiration
  bot/cogs/moderation/management.py
  bot/cogs/moderation/scheduler.py
  bot/utils/time.py
Labels: area: moderation, priority: 2 - normal, status: waiting for author, type: enhancement

#678 Antimalware: fix paste service URL showing replacement field
  bot/cogs/antimalware.py
Labels: area: frontend, priority: 3 - low, status: needs review, type: bug

#687 Fix tag fallback not respecting checks
  bot/cogs/error_handler.py
Labels: area: backend, priority: 1 - high, status: needs review, type: bug

#684 Kick users from voice when they get muted
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/scheduler.py
Labels: area: moderation, priority: 1 - high, status: needs review, type: enhancement

#681 Subclass Bot
  bot/__main__.py
  bot/api.py
  bot/bot.py
  bot/cogs/alias.py
  bot/cogs/antimalware.py
  bot/cogs/antispam.py
  bot/cogs/bot.py
  bot/cogs/clean.py
  bot/cogs/defcon.py
  bot/cogs/doc.py
  bot/cogs/duck_pond.py
  bot/cogs/error_handler.py
  bot/cogs/eval.py
  bot/cogs/extensions.py
  bot/cogs/filtering.py
  bot/cogs/free.py
  bot/cogs/help.py
  bot/cogs/information.py
  bot/cogs/jams.py
  bot/cogs/logging.py
  bot/cogs/moderation/__init__.py
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/management.py
  bot/cogs/moderation/modlog.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/off_topic_names.py
  bot/cogs/reddit.py
  bot/cogs/reminders.py
  bot/cogs/security.py
  bot/cogs/site.py
  bot/cogs/snekbox.py
  bot/cogs/sync/__init__.py
  bot/cogs/sync/cog.py
  bot/cogs/sync/syncers.py
  bot/cogs/tags.py
  bot/cogs/token_remover.py
  bot/cogs/utils.py
  bot/cogs/verification.py
  bot/cogs/watchchannels/__init__.py
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  bot/cogs/watchchannels/watchchannel.py
  bot/cogs/wolfram.py
  bot/interpreter.py
  tests/bot/cogs/test_duck_pond.py
  tests/bot/cogs/test_security.py
  tests/bot/cogs/test_token_remover.py
  tests/helpers.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: enhancement

#500 Token and bad code
  bot/cogs/bot.py
  bot/cogs/token_remover.py
Labels: area: filters, priority: 1 - high, status: needs review, type: bug

#693 Allow "recent" as infraction ID for infraction edit command
  bot/cogs/moderation/management.py
  bot/converters.py
Labels: area: moderation, priority: 3 - low, status: needs review, type: enhancement

#679 Display time left until expiration of infraction
  bot/cogs/moderation/management.py
  bot/utils/time.py
Labels: area: moderation, priority: 2 - normal, status: needs review, type: enhancement

#510 Use OAuth to be Reddit API compliant
  azure-pipelines.yml
  bot/cogs/reddit.py
  bot/constants.py
  config-default.yml
  docker-compose.yml
Labels: area: information, priority: 2 - normal, status: needs review, type: enhancement

#680 Added `unittest` for `bot.utils.time`
  bot/utils/time.py
  tests/bot/utils/test_time.py
Labels: area: tests, priority: 1 - high, status: needs review

#691 Clean command improvements
  bot/cogs/clean.py
Labels: area: utility, priority: 2 - normal, status: needs review, type: enhancement

#692 Allow mods+ to use commands and delete bots' messages in checkpoint channel
  bot/cogs/verification.py
Labels: area: moderation, priority: 2 - normal, status: needs review, type: enhancement

#694 Moderation: show emoji for DM failure instead of mentioning actor
  bot/cogs/moderation/scheduler.py
  bot/constants.py
  config-default.yml
Labels: area: frontend, priority: 2 - normal, status: needs review, type: enhancement

#696 Use OAuth to be Reddit API compliant
  azure-pipelines.yml
  bot/cogs/reddit.py
  bot/constants.py
  config-default.yml
  docker-compose.yml
Labels: area: information, priority: 2 - normal, type: enhancement

#703 Properly sync users to the database when they update their information
  bot/cogs/sync/cog.py
Labels: area: backend, priority: 0 - critical, type: bug

#683 Whitelist Discord Testers invite link
  config-default.yml
Labels: area: filters, priority: 3 - low, status: needs review, type: feature
