Repository python-discord/bot, pull requests merged in 2020-05, with the labels that each got.

#922 Display animated avatars in the user info command
  bot/cogs/information.py
  tests/bot/cogs/test_information.py
Labels: area: information, priority: 3 - low, status: needs review, type: bug

#919 Log unhandled errors from event listeners
  bot/bot.py
Labels: area: backend, priority: 1 - high, status: needs review, type: bug

#903 Use selector event loop on Windows
  bot/__init__.py
  bot/bot.py
Labels: area: backend, priority: 0 - critical, status: needs review, type: bug

#923 Remove the mention command
  bot/cogs/utils.py
  bot/constants.py
  config-default.yml
Labels: area: utility, priority: 3 - low, status: needs review, type: feature

#938 Add remindme alias for the remind command
  bot/cogs/reminders.py
Labels: area: utility, priority: 3 - low, status: needs review, type: feature

#924 Perma Bans now Overwrite Temp Bans
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/moderation/utils.py
Labels: area: backend, area: moderation, level: 1 - intermediate, priority: 1 - high, status: needs review

#899 Python News implemention
  Pipfile
  Pipfile.lock
  bot/__init__.py
  bot/__main__.py
  bot/cogs/python_news.py
  bot/constants.py
  config-default.yml
Labels: area: dependencies, area: information, priority: 2 - normal, status: needs review, type: feature

#946 add "solved" as a alias for "closed"
  bot/cogs/help_channels.py
Labels: area: help channels

#519 Refactor the !help command.
  bot/cogs/help.py
  bot/cogs/wolfram.py
  bot/decorators.py
  bot/pagination.py
Labels: area: information, priority: 3 - low, status: needs review, type: feature

#949 Use `send_help` to ensure that our help command is correctly invoked
  bot/cogs/bot.py
  bot/cogs/clean.py
  bot/cogs/defcon.py
  bot/cogs/error_handler.py
  bot/cogs/eval.py
  bot/cogs/extensions.py
  bot/cogs/moderation/management.py
  bot/cogs/off_topic_names.py
  bot/cogs/reddit.py
  bot/cogs/reminders.py
  bot/cogs/site.py
  bot/cogs/snekbox.py
  bot/cogs/utils.py
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  tests/bot/cogs/test_snekbox.py
Labels: area: information, priority: 0 - critical, type: bug

#858 Add mutability.md tag
  bot/resources/tags/mutability.md
Labels: area: information, status: waiting for author

#944 Increase snekbox re eval timeout to 30 seconds
  bot/cogs/snekbox.py
  tests/bot/cogs/test_snekbox.py
Labels: area: utility, priority: 3 - low, status: needs review, type: feature

#942 Python News: Implement stats
  bot/cogs/python_news.py
Labels: area: information, type: feature

#945 Add more statistics
  bot/cogs/bot.py
  bot/cogs/snekbox.py
  bot/cogs/stats.py
Labels: area: backend, priority: 2 - normal, status: waiting for author, type: feature

#934 Filtering: don't delete messages in DMs
  bot/cogs/filtering.py
Labels: area: filters, priority: 2 - normal, status: needs review, type: bug

#956 Help System: Move dormant faster if help channel is empty
  bot/cogs/help_channels.py
  bot/constants.py
  config-default.yml
Labels: area: help channels, priority: 1 - high, status: waiting for author, type: feature

#936 Filtering: don't attempt to send additional embeds for invalid invites
  bot/cogs/filtering.py
Labels: area: filters, priority: 2 - normal, status: needs review, type: bug

#866 feature to restrict tags to specific role(s)
  bot/cogs/tags.py
Labels: area: frontend, area: information, priority: 2 - normal, status: needs review, type: feature

#961 Permit moderation commands in ModMail category
  bot/cogs/error_handler.py
  bot/cogs/information.py
  bot/cogs/moderation/management.py
  bot/cogs/verification.py
  bot/constants.py
  bot/decorators.py
  bot/utils/checks.py
  tests/bot/cogs/test_information.py
  tests/bot/test_decorators.py
  tests/bot/utils/test_checks.py
Labels: area: moderation, priority: 0 - critical, status: needs review, type: feature

#947 RedisCache - Data Persistence
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
  bot/bot.py
  bot/cogs/antispam.py
  bot/cogs/defcon.py
  bot/cogs/duck_pond.py
  bot/cogs/help_channels.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/silence.py
  bot/cogs/stats.py
  bot/cogs/utils.py
  bot/cogs/watchchannels/talentpool.py
  bot/cogs/watchchannels/watchchannel.py
  bot/constants.py
  bot/pagination.py
  bot/utils/__init__.py
  bot/utils/messages.py
  bot/utils/redis_cache.py
  config-default.yml
  docker-compose.yml
  tests/bot/cogs/test_duck_pond.py
  tests/bot/cogs/test_snekbox.py
  tests/bot/test_constants.py
  tests/bot/utils/test_redis_cache.py
  tests/helpers.py
Labels: area: backend, area: dependencies, priority: 1 - high, status: needs review, type: feature

#966 Remove status emojis from help channels to prevent us from hitting rate limits
  bot/cogs/help_channels.py
Labels: area: help channels, priority: 0 - critical, status: needs review, type: bug

#930 Add tests for the antimalware cog
  bot/cogs/antimalware.py
  tests/bot/cogs/test_antimalware.py
Labels: area: tests, priority: 2 - normal, status: needs review, type: feature

#864 Ban and kick reason length fix
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/modlog.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/moderation/utils.py
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  bot/cogs/watchchannels/watchchannel.py
  tests/bot/cogs/moderation/test_infractions.py
  tests/bot/cogs/moderation/test_modlog.py
  tests/helpers.py
Labels: area: moderation, priority: 2 - normal, status: waiting for author, type: bug

#971 Remove the periodic ping from #verification
  bot/cogs/verification.py
Labels: area: backend, priority: 1 - high, status: needs review, type: feature

#973 Link #how-to-get-help in !free tag
  bot/resources/tags/free.md
Labels: area: frontend, area: information, priority: 3 - low, status: needs review, type: feature

#974 Add multichannel !purge
  bot/cogs/clean.py
Labels: area: moderation, priority: 1 - high, status: waiting for author, type: feature
