Repository python-discord/bot, pull requests merged in 2020-10, with the labels that each got.

#1200 Remove null chars before posting deleted messages
  bot/exts/moderation/modlog.py
Labels: a: moderation, p: 2 - normal, t: bug

#1199 Catch 404 in wait_for_deletion when reacting
  bot/utils/messages.py
Labels: a: backend, p: 3 - low, t: bug

#1201 Duck pond: ignore reactions in DMs
  bot/exts/fun/duck_pond.py
Labels: a: fun, p: 3 - low, t: bug

#1198 Remove alias cog
  bot/exts/backend/alias.py
  bot/exts/info/source.py
Labels: a: backend, p: 3 - low, t: feature

#1206 Move PEP command embed URL to title
  bot/exts/utils/utils.py
Labels: a: frontend, p: 2 - normal

#1205 Escape markdown in faulty source commands
  bot/exts/info/source.py
Labels: a: information, p: 3 - low, t: bug

#860 discord.py 1.3.x Functionality Migrating
  bot/__main__.py
  bot/exts/fun/off_topic_names.py
  bot/exts/info/doc.py
  bot/exts/info/reddit.py
  bot/exts/info/tags.py
  bot/exts/moderation/infraction/management.py
  bot/exts/utils/reminders.py
  bot/exts/utils/snekbox.py
  bot/patches/__init__.py
  bot/patches/message_edited_at.py
  tests/bot/exts/backend/sync/test_cog.py
  tests/bot/exts/info/test_information.py
  tests/bot/exts/moderation/test_silence.py
  tests/bot/exts/utils/test_snekbox.py
  tests/bot/patches/__init__.py
Labels: p: 2 - normal, t: feature

#1208 Reminder: no feedback message when no mention is used
  bot/exts/utils/reminders.py
Labels: a: utility, t: feature

#1207 Fix typos in bot/ docstrings and comments
  bot/exts/help_channels.py
  bot/exts/info/help.py
  bot/exts/info/information.py
  bot/exts/utils/bot.py
Labels: a: docs, p: 3 - low, t: bug

#835 Fix reminders sending duplicate DELETE request and cancelling themselves
  bot/decorators.py
  bot/errors.py
  bot/exts/backend/error_handler.py
  bot/exts/moderation/infraction/infractions.py
  bot/exts/utils/reminders.py
  bot/utils/function.py
  bot/utils/lock.py
Labels: a: utility, p: 2 - normal, t: bug

#1196 Introduction of discord.py 1.5.x
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/exts/info/information.py
  bot/exts/info/stats.py
  tests/bot/exts/info/test_information.py
Labels: a: dependencies, p: 1 - high, t: feature

#1211 Improvements for the rules command
  bot/exts/info/site.py
Labels: a: information, a: moderation, p: 2 - normal, t: feature

#1215 Support alternate gating methods
  bot/exts/moderation/verification.py
Labels: a: moderation, p: 1 - high, t: feature

#1216 Fix old nick in superstarify reason
  bot/exts/moderation/infraction/superstarify.py
Labels: a: moderation, t: bug

#1209 Send attachments improvements
  bot/exts/moderation/dm_relay.py
  bot/utils/messages.py
Labels: a: backend, a: moderation, p: 2 - normal, t: bug

#1222 Fix millisecond time for command processing time
  bot/exts/utils/ping.py
Labels: needs 1 approval, p: 2 - normal, t: bug

#1220 Add the ability to purge and ban in one command.
  bot/exts/moderation/infraction/infractions.py
Labels: a: moderation, p: 2 - normal, t: feature

#1165 Smart syncing of Users
  bot/exts/backend/sync/_syncers.py
  tests/bot/exts/backend/sync/test_users.py
Labels: a: backend, p: 1 - high, t: feature

#1227 Duckpond: Add a list of already ducked messages
  bot/exts/fun/duck_pond.py
Labels: a: fun, p: 1 - high, t: bug

#1231 Fixed hardcoded prefix in __main__.py
  bot/__main__.py
Labels: needs 1 approval

#886 Code block detection rewrite
  LICENSE-THIRD-PARTY
  bot/constants.py
  bot/exts/help_channels.py
  bot/exts/info/codeblock/__init__.py
  bot/exts/info/codeblock/_cog.py
  bot/exts/info/codeblock/_instructions.py
  bot/exts/info/codeblock/_parsing.py
  bot/exts/info/stats.py
  bot/exts/utils/bot.py
  bot/utils/__init__.py
  bot/utils/channel.py
  bot/utils/helpers.py
  config-default.yml
Labels: a: information, p: 2 - normal, t: bug, t: feature

#1233 Verification: add note to kicked members
  bot/exts/moderation/verification.py
Labels: a: backend, a: moderation, p: 2 - normal

#1242 Whitelist Core Dev Sprinters from our filters
  bot/constants.py
  bot/exts/filters/antimalware.py
  bot/exts/filters/antispam.py
  config-default.yml
Labels: a: filters, l: 0 - beginner, p: 0 - critical

#1157 Reddit: restrict nsfw subreddit(s)
  bot/exts/info/reddit.py
Labels: a: information, p: 1 - high, t: feature

#1240 display inf id actioned in mod channel
  bot/exts/moderation/infraction/_scheduler.py
Labels: a: backend, a: moderation, p: 2 - normal

#1246 Voice gate dm failed
  bot/exts/moderation/infraction/infractions.py
  bot/exts/moderation/voice_gate.py
Labels: needs 1 approval

#1243 Centralized handling of mod channel check
  bot/constants.py
  bot/exts/info/information.py
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/management.py
  bot/utils/channel.py
  config-default.yml
Labels: a: backend, a: moderation, p: 2 - normal

#1113 Cache silences to enable rescheduling and revoking reaction permissions
  LICENSE-THIRD-PARTY
  bot/exts/moderation/silence.py
  bot/exts/utils/reminders.py
  tests/_autospec.py
  tests/bot/exts/moderation/test_silence.py
  tests/helpers.py
Labels: a: moderation, a: tests, p: 2 - normal, t: bug, t: feature

#1253 Added voice_chat to eval list
  bot/constants.py
  bot/exts/utils/snekbox.py
  config-default.yml
Labels: a: utility, p: 2 - normal

#1250 Add handling of off-server users to user command
  bot/exts/info/information.py
Labels: a: information, t: feature

#1212 Added interleaving text in code blocks option
  bot/exts/utils/snekbox.py
  tests/bot/exts/utils/test_snekbox.py
Labels: a: utility, p: 2 - normal, t: feature

#1248 Set async-rediscache logging level to warning
  bot/__init__.py
Labels: a: backend, p: 2 - normal

#1257 Shorter `!code` message
  bot/resources/tags/codeblock.md
Labels: a: tags, t: feature
