Repository python-discord/bot, pull requests merged in 2020-04, with the labels that each got.

#832 Update token filter logging to match expanded detection
  bot/cogs/token_remover.py
Labels: area: filters, priority: 3 - low, status: needs review, type: bug

#813 Cache all Python dependencies in CI
  azure-pipelines.yml
Labels: area: CI, priority: 2 - normal, status: needs review, type: feature

#871 Add status emojis to help channels and improve bottom sorting
  bot/cogs/help_channels.py
  config-default.yml
Labels: area: frontend, priority: 0 - critical, type: feature

#873 Mitigate available help channels failing to synchronize their permissions
  bot/cogs/help_channels.py
Labels: area: backend, priority: 0 - critical, status: needs review, type: bug

#876 StatsD integration
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/async_stats.py
  bot/bot.py
  bot/cogs/antispam.py
  bot/cogs/defcon.py
  bot/cogs/error_handler.py
  bot/cogs/filtering.py
  bot/cogs/help_channels.py
  bot/cogs/stats.py
  bot/cogs/tags.py
  bot/cogs/token_remover.py
  bot/cogs/webhook_remover.py
  bot/constants.py
  config-default.yml
Labels: area: backend, priority: 2 - normal, status: needs review, type: feature

#868 Implement help system feedback.
  bot/__init__.py
  bot/cogs/help_channels.py
Labels: priority: 0 - critical, status: waiting for author, type: feature

#881 Reverse deletion of `!dormant` invocation messages
  bot/cogs/help_channels.py
Labels: area: frontend, priority: 1 - high

#874 Fix wrong exception type in syncing
  bot/cogs/sync/syncers.py
  tests/bot/cogs/sync/test_base.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: bug

#877 HelpChannels: fix AttributeError getting a category for a DMChannel
  bot/cogs/help_channels.py
Labels: priority: 2 - normal, status: needs review, type: bug

#875 Explicitly use UTF-8 to read tag files
  bot/cogs/tags.py
Labels: area: information, priority: 1 - high, status: needs review, type: bug

#896 Answered help session statistics
  bot/cogs/help_channels.py
Labels: area: frontend, priority: 2 - normal, type: feature

#885 Use a role overwrite to keep track of help channel cooldowns
  bot/cogs/help_channels.py
  bot/constants.py
  config-default.yml
Labels: area: frontend, priority: 0 - critical, status: needs review, type: feature

#895 Allowing `!eval` in help channels
  bot/cogs/error_handler.py
  bot/cogs/information.py
  bot/cogs/snekbox.py
  bot/cogs/utils.py
  bot/cogs/verification.py
  bot/decorators.py
  tests/bot/cogs/test_cogs.py
  tests/bot/cogs/test_information.py
  tests/bot/test_decorators.py
  tests/helpers.py
Labels: area: utility, priority: 1 - high, status: needs review, type: feature

#913 Sort help channels and add support for `how-to-get-help` channel
  bot/cogs/help_channels.py
  bot/constants.py
  config-default.yml
Labels: area: frontend, priority: 1 - high, status: needs review, type: feature
