Repository python-discord/bot, pull requests merged in 2020-09, with the labels that each got.

#1123 Use wait_for_deletion from bot/utils/messages.py rather than help_cleanup
  bot/cogs/help.py
Labels: a: information, p: 3 - low, t: feature

#1141 Added checks to ignore webhook and bot messages
  bot/cogs/antimalware.py
  tests/bot/cogs/test_antimalware.py
Labels: a: filters, p: 2 - normal, t: bug

#1134 Completely gutted the wolfram command.
  bot/__main__.py
  bot/cogs/wolfram.py
  bot/constants.py
  bot/pagination.py
  config-default.yml
  tests/bot/test_pagination.py
Labels: a: information, p: 2 - normal

#1135 Auto-respond to everyone pings.
  bot/cogs/antispam.py
  bot/rules/__init__.py
  bot/rules/everyone_ping.py
  config-default.yml
Labels: a: moderation, p: 0 - critical, t: feature

#1132 AntiSpam: ignore custom emojis in code blocks
  bot/rules/discord_emojis.py
Labels: a: filters, p: 2 - normal, t: bug

#1144 Move bolding markdown outside of text link in help channel messages.
  bot/cogs/help_channels.py
Labels: a: frontend, p: 3 - low, t: bug

#1077 Take steps to increase verification rate
  bot/cogs/verification.py
  bot/constants.py
  bot/rules/burst_shared.py
  config-default.yml
Labels: a: filters, a: moderation, p: 2 - normal

#927 Truncate internal eval.
  bot/cogs/eval.py
  bot/cogs/snekbox.py
  bot/utils/__init__.py
  bot/utils/helpers.py
  bot/utils/services.py
  tests/bot/cogs/test_snekbox.py
  tests/bot/utils/test_services.py
Labels: a: utility, p: 2 - normal, t: bug

#1158 Updated the names of reddit emotes
  config-default.yml
Labels: needs 2 approvals

#817 Writing tests for moderation utils.
  bot/exts/moderation/infraction/_utils.py
  tests/bot/exts/moderation/infraction/test_utils.py
Labels: a: tests, p: 2 - normal

#1150 Implement with(out)_role checks and decorators using has_any_role
  bot/decorators.py
  bot/exts/filters/filter_lists.py
  bot/exts/fun/off_topic_names.py
  bot/exts/help_channels.py
  bot/exts/info/doc.py
  bot/exts/info/information.py
  bot/exts/info/reddit.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/dm_relay.py
  bot/exts/moderation/infraction/infractions.py
  bot/exts/moderation/infraction/management.py
  bot/exts/moderation/infraction/superstarify.py
  bot/exts/moderation/silence.py
  bot/exts/moderation/slowmode.py
  bot/exts/moderation/verification.py
  bot/exts/moderation/watchchannels/bigbrother.py
  bot/exts/moderation/watchchannels/talentpool.py
  bot/exts/utils/bot.py
  bot/exts/utils/clean.py
  bot/exts/utils/eval.py
  bot/exts/utils/extensions.py
  bot/exts/utils/jams.py
  bot/exts/utils/reminders.py
  bot/exts/utils/utils.py
  bot/utils/checks.py
  tests/bot/exts/moderation/test_silence.py
  tests/bot/exts/moderation/test_slowmode.py
  tests/bot/utils/test_checks.py
Labels: a: backend, p: 3 - low, t: feature

#1145 Fix @everyone ping rule.
  bot/constants.py
  bot/exts/filters/antispam.py
  bot/exts/filters/filtering.py
  bot/rules/__init__.py
  bot/rules/everyone_ping.py
  config-default.yml
Labels: a: filters, a: tests, p: 1 - high, t: bug

#1164 Several improvements to duckpond
  bot/constants.py
  bot/exts/fun/duck_pond.py
  config-default.yml
  tests/bot/exts/fun/__init__.py
  tests/bot/exts/fun/test_duck_pond.py
Labels: p: 3 - low, t: bug

#1163 Use `async-rediscache` package for our redis caches
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/bot.py
  bot/exts/filters/filtering.py
  bot/exts/help_channels.py
  bot/exts/moderation/dm_relay.py
  bot/exts/moderation/verification.py
  bot/utils/__init__.py
  bot/utils/redis_cache.py
  tests/bot/utils/test_redis_cache.py
  tests/helpers.py
Labels: a: backend, a: dependencies, l: 0 - beginner, p: 2 - normal

#1168 Latency cog for checking ping.
  Pipfile
  Pipfile.lock
  bot/exts/utils/ping.py
Labels: a: utility, p: 3 - low, t: feature

#1061 Use mentions for users in mod logs and infraction search results
  bot/converters.py
  bot/exts/filters/antispam.py
  bot/exts/filters/filtering.py
  bot/exts/filters/token_remover.py
  bot/exts/filters/webhook_remover.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/infractions.py
  bot/exts/moderation/infraction/management.py
  bot/exts/moderation/infraction/superstarify.py
  bot/exts/moderation/modlog.py
  bot/exts/moderation/verification.py
  bot/exts/utils/clean.py
  bot/utils/messages.py
  tests/bot/exts/filters/test_token_remover.py
Labels: a: frontend, a: moderation, p: 3 - low, t: feature

#1126 Whitelist the modmail category for displaying verbose infraction info from the user command
  bot/constants.py
  bot/exts/info/information.py
  bot/exts/moderation/infraction/_scheduler.py
  config-default.yml
  tests/bot/exts/info/test_information.py
Labels: a: information, a: moderation, p: 2 - normal, t: bug, t: feature

#1171 Adjust verification & incidents log levels
  bot/exts/moderation/incidents.py
  bot/exts/moderation/verification.py
Labels: a: backend, a: moderation, p: 3 - low

#1161 Add userid decoding and user token detection to the token removal moderation feature
  bot/exts/filters/token_remover.py
  tests/bot/exts/filters/test_token_remover.py
Labels: a: filters, a: frontend, a: moderation, t: feature

#1151 Sync: remove confirmation
  bot/constants.py
  bot/exts/backend/sync/_syncers.py
  config-default.yml
  tests/bot/exts/backend/sync/test_base.py
Labels: a: backend, p: 2 - normal, t: feature

#1191 Verification: broaden 50_007 error code handling to all Discord exception types
  bot/exts/moderation/incidents.py
  bot/exts/moderation/verification.py
Labels: a: backend, a: moderation, p: 2 - normal
