Repository python-discord/bot, pull requests merged in 2020-01, with the labels that each got.

#714 Watchchannels: show username in response for already watched users
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
Labels: area: moderation, priority: 3 - low, status: needs review, type: feature

#705 Moderation: explicitly set active value when posting infractions
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/watchchannels/bigbrother.py
Labels: area: API, priority: 0 - critical, status: needs review, type: bug

#722 Set up a Prometheus endpoint for metrics
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/bot.py
  bot/cogs/metrics.py
Labels: area: backend, type: feature

#723 Allow for throw away words after the rules command call
  bot/cogs/alias.py
Labels: priority: 3 - low, status: needs review, type: feature

#725 Track command completions.
  bot/cogs/metrics.py
Labels: area: backend, type: feature

#726 Prometheus: track command completions by user.
  bot/cogs/metrics.py
Labels: area: backend, type: feature

#728 Fix intersphinx not getting an user agent for requests
  bot/cogs/doc.py
Labels: area: information, priority: 0 - critical, type: bug

#686 Log voice channel events
  bot/cogs/moderation/modlog.py
  bot/constants.py
  config-default.yml
Labels: area: moderation, priority: 2 - normal, status: needs review, type: feature

#701 Support applying infractions to users not in the DB via Converter `FetchedUser`
  bot/cogs/alias.py
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/management.py
  bot/cogs/moderation/modlog.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/moderation/utils.py
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  bot/cogs/watchchannels/watchchannel.py
  bot/converters.py
Labels: area: moderation, priority: 1 - high, status: needs review, type: bug

#730 Fix user command error for empty custom status
  bot/cogs/information.py
Labels: area: utility, type: bug
