Repository python-discord/bot, pull requests merged in 2020-07, with the labels that each got.

#1021 Slowmode command
  bot/cogs/moderation/__init__.py
  bot/cogs/moderation/slowmode.py
  bot/converters.py
  bot/utils/time.py
  tests/bot/cogs/test_slowmode.py
Labels: a: moderation, a: utility, p: 2 - normal, t: feature

#1000 ModLog: fix AttributeError in on_member_update
  bot/cogs/moderation/modlog.py
Labels: a: moderation, p: 2 - normal, t: bug

#1035 Add range-len tag
  bot/resources/tags/range-len.md
Labels: a: tags, p: 2 - normal, t: feature

#1017 Scheduler Redesign
  bot/cogs/filtering.py
  bot/cogs/help_channels.py
  bot/cogs/moderation/management.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/silence.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/reminders.py
  bot/utils/scheduling.py
Labels: a: backend, p: 1 - high, t: feature

#1039 Allow role mentions in specific areas
  bot/cogs/help_channels.py
  bot/cogs/moderation/modlog.py
  bot/cogs/sync/syncers.py
  config-default.yml
Labels: a: backend, p: 0 - critical, t: bug

#1032 Sanitize bot output
  bot/cogs/error_handler.py
  bot/cogs/filtering.py
  bot/cogs/snekbox.py
  tests/bot/cogs/test_snekbox.py
Labels: a: backend, a: utility, p: 0 - critical, t: bug

#1051 Suppress NotFound when removing help command reactions
  bot/cogs/help.py
Labels: a: information, p: 3 - low, t: bug

#1044 Allow ordering talentpool/bigbrother watched users by oldest added
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  bot/cogs/watchchannels/watchchannel.py
Labels: a: moderation, p: 2 - normal, t: feature

#1041 Relay all DMs sent to the bot to #dm_log
  bot/__main__.py
  bot/cogs/dm_relay.py
  bot/cogs/duck_pond.py
  bot/cogs/python_news.py
  bot/constants.py
  bot/utils/webhooks.py
  config-default.yml
  tests/bot/cogs/test_duck_pond.py
Labels: p: 3 - low, t: feature

#1054 DM relay - minor fixes
  bot/cogs/dm_relay.py
  bot/converters.py
Labels: a: backend, p: 1 - high, t: bug

#1045 Invoke fuzzywuzzy's processor before matching
  bot/cogs/help.py
Labels: a: information, p: 3 - low, t: bug

#1046 Update or-gotcha.md
  bot/resources/tags/or-gotcha.md
Labels: a: tags, p: 2 - normal

#993 Implement #incidents channel automation
  bot/cogs/moderation/__init__.py
  bot/cogs/moderation/incidents.py
  bot/constants.py
  config-default.yml
  tests/bot/cogs/moderation/test_incidents.py
Labels: a: moderation, p: 2 - normal, t: feature

#955 Source command
  bot/__main__.py
  bot/cogs/source.py
  bot/cogs/tags.py
Labels: a: information, p: 3 - low, t: feature

#1060 Remove eval py formatting
  bot/cogs/snekbox.py
  tests/bot/cogs/test_snekbox.py
Labels: a: utility, p: 3 - low, t: feature

#1056 Role reminders
  bot/cogs/reminders.py
  bot/utils/messages.py
Labels: a: utility, p: 2 - normal, t: feature

#957 Code Jams unit tests
  bot/cogs/jams.py
  tests/bot/cogs/test_jams.py
Labels: a: tests, p: 2 - normal

#1063 Support multiple categories for code jam team creation
  bot/cogs/jams.py
  tests/bot/cogs/test_jams.py
Labels: a: utility, p: 0 - critical, t: bug

#1062 Truncate charinfo results
  bot/cogs/utils.py
Labels: a: frontend, a: utility, p: 3 - low, t: bug

#1064 Check that embed desc is not Empty before stripping.
  bot/cogs/help_channels.py
Labels: p: 3 - low, t: bug

#1023 Help System: Implement question message pinning
  bot/cogs/help_channels.py
Labels: a: help channels, p: 2 - normal, t: feature

#1073 Change regex so it catches new discord URL
  bot/cogs/webhook_remover.py
Labels: a: filters, p: 2 - normal, t: bug
