Repository python-discord/bot, pull requests merged in 2020-02, with the labels that each got.

#736 Update config-default.yml - Allow .md files
  config-default.yml
Labels: priority: 3 - low, status: needs review, type: feature

#630 Relay attachments to log channel before filters delete message
  bot/cogs/antispam.py
  bot/cogs/moderation/modlog.py
  bot/constants.py
  bot/utils/messages.py
  config-default.yml
Labels: area: API, area: filters, priority: 3 - low, status: waiting for author, type: feature

#737 Remove prometheus related code
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/bot.py
  bot/cogs/metrics.py
Labels: area: dependencies, status: needs review

#542 Make it easier for user to search for tags
  bot/cogs/tags.py
Labels: area: information, priority: 3 - low, status: needs review, type: feature

#743 Update discord.py to 1.3.1
  Pipfile
  Pipfile.lock
Labels: area: dependencies, priority: 2 - normal, status: needs review

#625 Separate message/embed deletion and reaction deletion emojis
  bot/cogs/help.py
  bot/constants.py
  bot/pagination.py
  bot/utils/messages.py
  config-default.yml
Labels: area: frontend, priority: 2 - normal, status: waiting for author, type: feature

#753 Show created date and duration in expired infraction log
  bot/cogs/moderation/scheduler.py
  bot/utils/time.py
Labels: area: frontend, area: moderation, priority: 3 - low, status: needs review, type: feature

#761 Refactor logging setup to be more explicit and cleaner.
  Pipfile
  Pipfile.lock
  bot/__init__.py
  tox.ini
Labels: area: backend, area: dependencies, priority: 1 - high, status: needs review, type: bug

#762 Sentry SDK setup
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
  bot/__main__.py
  bot/api.py
  bot/bot.py
  bot/cogs/error_handler.py
  bot/constants.py
  config-default.yml
  tests/bot/test_api.py
Labels: area: backend, priority: 1 - high, status: needs review, type: feature

#733 Add test cases for antispam rules, fix bug in attachments rule & test
  bot/rules/attachments.py
  tests/bot/rules/__init__.py
  tests/bot/rules/test_attachments.py
  tests/bot/rules/test_burst.py
  tests/bot/rules/test_burst_shared.py
  tests/bot/rules/test_chars.py
  tests/bot/rules/test_discord_emojis.py
  tests/bot/rules/test_duplicates.py
  tests/bot/rules/test_links.py
  tests/bot/rules/test_mentions.py
  tests/bot/rules/test_newlines.py
  tests/bot/rules/test_role_mentions.py
Labels: area: tests, status: needs review

#772 Don't log exception traceback on Forbidden for welcomes.
  bot/cogs/verification.py
Labels: area: moderation, priority: 3 - low, status: needs review, type: bug

#759 Pagination migrations - Emoji Data Structure Modified
  bot/pagination.py
Labels: area: backend, priority: 3 - low, status: needs review, type: feature

#771 Fix paginator erroring on clearing reactions from non-existing messages.
  bot/pagination.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: bug

#741 Refactor information.py with lots of changes that makes the overall code cleaner and faster
  bot/cogs/information.py
  tests/bot/cogs/test_information.py
Labels: area: information, area: tests, priority: 2 - normal, status: needs review, type: feature

#774 Reduce log level of tag cooldown notice.
  bot/cogs/tags.py
Labels: area: information, priority: 3 - low, status: needs review, type: bug

#756 Fix missing Django logs when using Docker Compose
  docker-compose.yml
Labels: area: backend, priority: 3 - low, status: needs review, type: bug

#776 Change verification post log level to info, tidy code.
  bot/cogs/verification.py
Labels: area: moderation, priority: 3 - low, status: needs review, type: bug

#773 Check reminder user and channel before send and schedule.
  bot/cogs/reminders.py
Labels: area: utility, priority: 3 - low, status: needs review, type: bug

#749 Reminder Embed Enhancements & Whitelist Expansion
  bot/cogs/moderation/superstarify.py
  bot/cogs/reminders.py
  bot/constants.py
  config-default.yml
Labels: area: utility, priority: 3 - low, status: needs review, type: feature

#711 Prevent the role syncer from wiping the database table during API latency
  bot/api.py
  bot/bot.py
  bot/cogs/antispam.py
  bot/cogs/defcon.py
  bot/cogs/doc.py
  bot/cogs/duck_pond.py
  bot/cogs/logging.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/off_topic_names.py
  bot/cogs/reddit.py
  bot/cogs/reminders.py
  bot/cogs/sync/cog.py
  bot/cogs/sync/syncers.py
  bot/cogs/verification.py
  bot/cogs/watchchannels/watchchannel.py
  bot/constants.py
  config-default.yml
  tests/base.py
  tests/bot/cogs/sync/test_base.py
  tests/bot/cogs/sync/test_cog.py
  tests/bot/cogs/sync/test_roles.py
  tests/bot/cogs/sync/test_users.py
  tests/bot/cogs/test_duck_pond.py
  tests/helpers.py
Labels: area: backend, priority: 0 - critical, status: needs review, type: bug

#781 Reminders: don't cancel task if reminder is invalid when rescheduling
  bot/cogs/reminders.py
Labels: area: utility, priority: 2 - normal, status: needs review, type: bug

#790 Added ignoring staff to Antimalware check.
  bot/cogs/antimalware.py
Labels: area: filters, priority: 2 - normal, status: waiting for author, type: feature

#785 Verify channels against server and reddit OAuth2 in constants on startup.
  bot/__main__.py
  bot/cogs/config_verifier.py
  bot/cogs/reddit.py
  bot/constants.py
  bot/utils/__init__.py
  tests/bot/test_utils.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: feature

#798 Moderation: fix task cancellation for permanent infraction when editing
  bot/cogs/moderation/management.py
Labels: area: moderation, priority: 3 - low, status: needs review, type: bug

#782 Rename constants to match their guild counterparts
  bot/__main__.py
  bot/cogs/bot.py
  bot/cogs/clean.py
  bot/cogs/defcon.py
  bot/cogs/eval.py
  bot/cogs/extensions.py
  bot/cogs/free.py
  bot/cogs/help.py
  bot/cogs/information.py
  bot/cogs/jams.py
  bot/cogs/logging.py
  bot/cogs/moderation/modlog.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/snekbox.py
  bot/cogs/sync/syncers.py
  bot/cogs/tags.py
  bot/cogs/utils.py
  bot/cogs/verification.py
  bot/constants.py
  config-default.yml
  tests/bot/cogs/sync/test_base.py
  tests/bot/cogs/test_information.py
Labels: area: backend, priority: 2 - normal, status: needs review, type: feature

#757 Handle more types of CommandError
  bot/cogs/error_handler.py
  bot/cogs/moderation/infractions.py
Labels: area: backend, priority: 3 - low, status: needs review, type: feature

#710 Eval cog improvements
  bot/cogs/snekbox.py
  tests/bot/cogs/test_snekbox.py
  tests/helpers.py
Labels: area: frontend, area: tests, area: utility, priority: 1 - high, type: bug, type: feature

#797 Fix invalid tag names being passed to the tag cog.
  bot/cogs/error_handler.py
  bot/converters.py
  tests/bot/test_converters.py
Labels: area: information, priority: 2 - normal, status: needs review, type: bug

#755 Don't suppress all errors in scheduler
  bot/cogs/moderation/management.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/reminders.py
  bot/utils/scheduling.py
Labels: area: backend, priority: 1 - high, status: needs review, type: bug
