Repository python-discord/bot, pull requests merged in 2020-03, with the labels that each got.

#806 Coloured log output
  Pipfile
  Pipfile.lock
  bot/__init__.py
Labels: area: frontend, priority: 2 - normal, status: needs review, type: feature

#808 Optimize Dockerfile for faster rebuilds
  Dockerfile
Labels: status: needs review

#783 Migrate bot to Python 3.8
  Dockerfile
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
  bot/cogs/sync/syncers.py
  tests/base.py
  tests/bot/cogs/sync/test_base.py
  tests/bot/cogs/sync/test_cog.py
  tests/bot/cogs/sync/test_roles.py
  tests/bot/cogs/sync/test_users.py
  tests/bot/cogs/test_duck_pond.py
  tests/bot/cogs/test_information.py
  tests/bot/cogs/test_snekbox.py
  tests/bot/cogs/test_token_remover.py
  tests/bot/rules/__init__.py
  tests/bot/rules/test_attachments.py
  tests/bot/rules/test_burst.py
  tests/bot/rules/test_burst_shared.py
  tests/bot/rules/test_chars.py
  tests/bot/rules/test_discord_emojis.py
  tests/bot/rules/test_duplicates.py
  tests/bot/rules/test_links.py
  tests/bot/rules/test_mentions.py
  tests/bot/rules/test_newlines.py
  tests/bot/rules/test_role_mentions.py
  tests/bot/test_api.py
  tests/bot/utils/test_time.py
  tests/helpers.py
  tests/test_base.py
  tests/test_helpers.py
  tests/utils/test_time.py
Labels: area: dependencies, priority: 2 - normal, status: needs review, type: feature

#750 Create AsyncResolver inside a coroutine to avoid DeprecationWarning
  bot/api.py
  bot/bot.py
Labels: area: backend, priority: 3 - low, status: needs review, type: bug

#811 Add more pre-commit hooks and run them in CI
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
  bot/cogs/free.py
  bot/utils/__init__.py
  tests/README.md
  tests/base.py
  tests/bot/cogs/sync/test_base.py
  tests/bot/cogs/test_snekbox.py
  tests/bot/test_utils.py
Labels: area: CI, area: dependencies, priority: 2 - normal, status: needs review, type: feature

#816 Use raw strings for docstrings with forward slashes
  bot/cogs/extensions.py
Labels: priority: 3 - low, status: needs review, type: bug

#814 Expand Antimalware User Feedback & Logging
  bot/cogs/antimalware.py
Labels: area: filters, priority: 2 - normal, status: needs review, type: feature

#807 Added Pagination to !roles command
  bot/cogs/information.py
  tests/bot/cogs/test_information.py
Labels: area: information, priority: 2 - normal, status: waiting for author, type: bug

#643 implement !zen command.
  bot/cogs/utils.py
Labels: area: information, priority: 3 - low, status: waiting for author, type: feature

#820 Pre-commit tweaks
  .pre-commit-config.yaml
  azure-pipelines.yml
Labels: area: CI, priority: 2 - normal, status: needs review, type: feature

#823 Subcommand `search` and `search any` to search inside tags' contents and not names.
  bot/cogs/tags.py
Labels: area: information, good first issue, priority: 3 - low, status: needs review, type: feature

#824 Fix filtered extension string out of scope for antismalware log message
  bot/cogs/antimalware.py
Labels: area: filters, priority: 1 - high, status: needs review, type: bug

#826 Implement vote command.
  bot/cogs/utils.py
Labels: area: utility, priority: 3 - low, status: needs review, type: feature

#825 Refactor token detection to check all potential substrings in message
  bot/cogs/token_remover.py
Labels: area: filters, priority: 2 - normal, status: needs review, type: bug

#822 ModLog: fix posting null attachments for deleted message logs
  bot/cogs/moderation/modlog.py
Labels: area: moderation, priority: 2 - normal, status: needs review, type: bug

#803 Removed API dependency for Tags
  bot/cogs/tags.py
  bot/resources/tags/args-kwargs.md
  bot/resources/tags/ask.md
  bot/resources/tags/class.md
  bot/resources/tags/classmethod.md
  bot/resources/tags/codeblock.md
  bot/resources/tags/decorators.md
  bot/resources/tags/dictcomps.md
  bot/resources/tags/enumerate.md
  bot/resources/tags/except.md
  bot/resources/tags/exit().md
  bot/resources/tags/f-strings.md
  bot/resources/tags/foo.md
  bot/resources/tags/functions-are-objects.md
  bot/resources/tags/global.md
  bot/resources/tags/if-name-main.md
  bot/resources/tags/indent.md
  bot/resources/tags/inline.md
  bot/resources/tags/iterate-dict.md
  bot/resources/tags/listcomps.md
  bot/resources/tags/mutable-default-args.md
  bot/resources/tags/names.md
  bot/resources/tags/off-topic.md
  bot/resources/tags/open.md
  bot/resources/tags/or-gotcha.md
  bot/resources/tags/param-arg.md
  bot/resources/tags/paste.md
  bot/resources/tags/pathlib.md
  bot/resources/tags/pep8.md
  bot/resources/tags/positional-keyword.md
  bot/resources/tags/precedence.md
  bot/resources/tags/quotes.md
  bot/resources/tags/relative-path.md
  bot/resources/tags/repl.md
  bot/resources/tags/return.md
  bot/resources/tags/round.md
  bot/resources/tags/scope.md
  bot/resources/tags/seek.md
  bot/resources/tags/self.md
  bot/resources/tags/star-imports.md
  bot/resources/tags/traceback.md
  bot/resources/tags/windows-path.md
  bot/resources/tags/with.md
  bot/resources/tags/xy-problem.md
  bot/resources/tags/ytdl.md
  bot/resources/tags/zen.md
  bot/resources/tags/zip.md
Labels: area: information, priority: 2 - normal, status: waiting for author, type: feature

#828 Test for command name and alias shadowing
  tests/bot/cogs/test_cogs.py
Labels: area: tests, priority: 2 - normal, status: needs review, type: feature

#830 ModLog Channel Update formatting fix.
  bot/cogs/moderation/modlog.py
Labels: area: frontend, priority: 3 - low, type: bug

#530 Strip spoiler tags for watchlist triggers
  bot/cogs/filtering.py
  bot/cogs/moderation/modlog.py
Labels: area: filters, priority: 2 - normal, status: needs review, type: feature

#821 Automatically Remove Users from BigBrother Watch List on Perma Ban
  bot/cogs/moderation/infractions.py
  bot/cogs/verification.py
  bot/cogs/watchchannels/bigbrother.py
Labels: area: moderation, priority: 1 - high, status: needs review, type: bug

#837 Update contributor doc
  CONTRIBUTING.md
Labels: area: docs, priority: 1 - high, type: feature

#841 Remove unused safety & dodgy dev dependencies
  Pipfile
  Pipfile.lock
Labels: area: dependencies, priority: 3 - low, status: needs review

#840 Removed `zen` tag due `!zen` command exist.
  bot/resources/tags/zen.md
Labels: area: information, type: feature

#842 Fix snekbox's message parsing to extract code for re-evaluation
  bot/cogs/snekbox.py
  tests/bot/cogs/test_snekbox.py
Labels: area: utility, priority: 2 - normal, status: needs review, type: bug

#848 Hard-coded PEP 0 to !pep command
  bot/cogs/utils.py
Labels: area: information, priority: 3 - low, status: waiting for author, type: bug

#849 Discord Webhook URL removing
  bot/__main__.py
  bot/cogs/webhook_remover.py
Labels: area: filters, priority: 2 - normal, status: waiting for author, type: feature

#812 Implement silencer (hush) cog.
  bot/cogs/error_handler.py
  bot/cogs/moderation/__init__.py
  bot/cogs/moderation/silence.py
  bot/converters.py
  tests/bot/cogs/moderation/__init__.py
  tests/bot/cogs/moderation/test_silence.py
  tests/bot/test_converters.py
Labels: area: moderation, priority: 2 - normal, status: needs review, type: feature

#845 Logging Level Adjustments
  bot/cogs/alias.py
  bot/cogs/bot.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/superstarify.py
  bot/cogs/moderation/utils.py
  bot/cogs/snekbox.py
  bot/cogs/sync/syncers.py
  bot/converters.py
  bot/utils/messages.py
Labels: area: backend, priority: 3 - low, status: WIP

#833 Fixed !zen command exact word matching.
  bot/cogs/utils.py
Labels: area: utility, priority: 3 - low, status: needs review, status: stalled, type: feature

#846 Filtering: merge the word and token watch filters
  bot/cogs/filtering.py
  bot/constants.py
  config-default.yml
Labels: area: filters, priority: 2 - normal, status: needs review, type: feature

#854 Tags response + command message deletion with trashcan reaction
  bot/cogs/tags.py
Labels: priority: 2 - normal, status: waiting for author, type: feature

#852 Don't let change expiration time when infraction already expired.
  bot/cogs/moderation/management.py
Labels: area: moderation, priority: 2 - normal, status: needs review, type: bug
