Repository python-discord/bot, pull requests merged in 2020-12, with the labels that each got.

#1214 fix(statsd): Gracefully handle socket.gaierro in AsyncStatsClient
  bot/bot.py
Labels: a: backend, p: 2 - normal, t: bug

#1306 `!close` removes the cooldown role from the claimant
  bot/exts/help_channels/_cog.py
Labels: a: help channels, p: 2 - normal, t: bug

#1319 Relay the moderator's reason for `!superstarify` to the user
  bot/exts/moderation/infraction/superstarify.py
Labels: a: moderation

#1322 New `!verify` command to manually apply the Developer role
  bot/exts/moderation/verification.py
Labels: a: moderation

#1318 Create command for showing Discord snowflake creation time
  bot/exts/utils/utils.py
Labels: a: moderation, a: utility

#1274 Giving the user command more data from the Metricity database for moderators.
  bot/exts/info/information.py
  tests/bot/exts/info/test_information.py
Labels: a: moderation, a: utility

#1326 Fix backtick escapes in the codeblock tag
  bot/resources/tags/codeblock.md
Labels: a: tags, t: bug

#1329 Better handle native gated users
  bot/exts/moderation/verification.py
Labels: p: 0 - critical, t: feature

#1331 Use member update event for verification DMs
  Dockerfile
  Pipfile
  Pipfile.lock
  bot/exts/moderation/verification.py
Labels: a: backend, p: 0 - critical

#1333 Hopefully fix the API session being closed when populating the filter cache on startup
  bot/api.py
  bot/bot.py
  tests/bot/test_api.py
Labels: a: backend, p: 1 - high, t: bug

#1332 Sentry SDK version bump and Sentry release creation
  .github/workflows/build.yml
  .github/workflows/sentry_release.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  bot/constants.py
  bot/log.py
Labels: a: CI, a: dependencies, needs 1 approval

#1337 Move PEP command and utils to own cog, fix bug related not checking status and add GitHub token
  bot/constants.py
  bot/exts/info/pep.py
  bot/exts/utils/utils.py
  config-default.yml
Labels: a: utility, needs 2 approvals, p: 1 - high

#1328 Manual verification with `!verify` sends the user the confirmation DM.
  bot/exts/moderation/verification.py
Labels: a: moderation, needs 2 approvals

#1016 Some bug fixes
  bot/bot.py
  bot/exts/info/reddit.py
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/watchchannels/_watchchannel.py
Labels: a: backend, a: information, a: moderation, needs 1 approval, p: 3 - low, t: bug

#1334 Fix flake8 pre-commit hook running through PyCharm
  .pre-commit-config.yaml
Labels: needs 2 approvals, p: 2 - normal, t: bug
