Repository python-discord/bot, pull requests merged in 2020-08, with the labels that each got.

#1058 FilterLists: Manage whitelisting and blacklisting via the bot
  Pipfile
  Pipfile.lock
  bot/__main__.py
  bot/bot.py
  bot/cogs/antimalware.py
  bot/cogs/error_handler.py
  bot/cogs/filter_lists.py
  bot/cogs/filtering.py
  bot/cogs/off_topic_names.py
  bot/constants.py
  bot/converters.py
  bot/utils/regex.py
  config-default.yml
  tests/bot/cogs/test_antimalware.py
Labels: a: API, a: filters, needs 1 approval, p: 2 - normal, t: feature

#1078 Add support for plural FilterList types.
  bot/converters.py
Labels: a: API, p: 3 - low, t: feature

#1089 HelpChannels: use more reliable check for claimed channel
  bot/cogs/help_channels.py
Labels: a: help channels, p: 2 - normal, t: bug

#1088 Source: raise BadArgument for dynamically-created objects
  bot/cogs/source.py
Labels: a: utility, p: 3 - low, t: bug

#1091 RedisCache: remove erroneous `_redis` alias
  bot/utils/redis_cache.py
Labels: a: backend, p: 1 - high, t: bug

#1087 Cancel scheduled tasks when cogs unload
  bot/cogs/filtering.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/silence.py
  bot/cogs/reminders.py
Labels: a: backend, p: 2 - normal, t: bug

#1093 Deps: update discord.py to 1.4.0
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: a: dependencies, p: 2 - normal, t: feature

#1092 HelpChannels: clear claimant cache when channel goes dormant v2.0
  bot/cogs/help_channels.py
Labels: a: help channels, p: 2 - normal, t: bug

#1086 Help channel message pin fixes
  bot/cogs/help_channels.py
  config-default.yml
Labels: a: help channels, p: 2 - normal, t: bug

#1085 Utils: show error message for long poll titles
  bot/cogs/utils.py
Labels: a: frontend, a: utility, p: 3 - low, t: bug

#1084 Ignore webhooks for nickname filter
  bot/cogs/filtering.py
Labels: a: filters, p: 2 - normal, t: bug

#1097 Remove api endpoint config values.
  bot/constants.py
  config-default.yml
Labels: a: backend, p: 3 - low, t: feature

#1108 Escape Markdown in reddit post titles
  bot/cogs/reddit.py
Labels: a: frontend, p: 3 - low, t: bug

#1107 Don't patch ctx.message.author in antispam
  bot/cogs/antispam.py
  bot/cogs/moderation/modlog.py
  bot/cogs/moderation/scheduler.py
  bot/cogs/moderation/utils.py
Labels: a: filters, p: 2 - normal, t: bug

#1100 Filtering: ignore errors for duplicate offensive messages
  bot/cogs/filtering.py
Labels: a: filters, p: 3 - low, t: bug

#1109 Unnominate banned users from the talent pool
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
Labels: a: moderation, p: 2 - normal, t: bug

#1117 Make client parameter mandatory for wait_for_deletion
  bot/cogs/bot.py
  bot/cogs/snekbox.py
  bot/cogs/tags.py
  bot/utils/messages.py
Labels: a: backend, needs 1 approval, p: 3 - low, t: bug

#1116 Restrict reminder methods to authors and admins.
  bot/cogs/reminders.py
Labels: a: utility, p: 0 - critical, t: bug

#1124 Support specifying top-level aliases in the command decorator
  bot/__init__.py
  bot/bot.py
  bot/cogs/alias.py
  bot/cogs/defcon.py
  bot/cogs/extensions.py
  bot/cogs/help.py
  bot/cogs/site.py
  bot/cogs/watchchannels/bigbrother.py
  bot/cogs/watchchannels/talentpool.py
  bot/command.py
  tests/bot/cogs/test_cogs.py
Labels: a: backend, p: 3 - low, t: feature

#1118 Censor watchchannel messages when they contain leaked tokens
  bot/cogs/bot.py
  bot/cogs/watchchannels/watchchannel.py
Labels: a: moderation, p: 2 - normal, t: bug
