Repository python-discord/bot, pull requests merged in 2020-06, with the labels that each got.

#962 Remove all sending of avatar_hash
  bot/cogs/moderation/utils.py
  bot/cogs/sync/cog.py
  bot/cogs/sync/syncers.py
  tests/bot/cogs/sync/test_cog.py
  tests/bot/cogs/sync/test_users.py
Labels: area: API, priority: 0 - critical, status: needs review, type: feature

#984 Send infraction DM before applying infraction
  bot/cogs/moderation/scheduler.py
Labels: area: moderation, priority: 0 - critical, type: bug

#970 Add staff counts to !server
  bot/cogs/information.py
  tests/bot/cogs/test_information.py
Labels: area: frontend, priority: 3 - low, status: needs review, type: feature

#985 Stats: Implement rules stats
  bot/cogs/site.py
Labels: area: stats, priority: 2 - normal, status: needs review, type: feature

#983 Fix AttributeError for category check
  bot/cogs/stats.py
Labels: area: backend, priority: 3 - low, status: needs review, type: bug

#935 ModLog: ignore DMs in the message delete listener
  bot/cogs/moderation/modlog.py
Labels: area: moderation, priority: 2 - normal, status: waiting for author, type: bug

#988 Add snekbox to the Docker compose file
  docker-compose.yml
Labels: priority: 3 - low, status: waiting for author, type: feature

#910 Converters: handle ValueError when year for duration is out of range
  bot/converters.py
  tests/bot/test_converters.py
Labels: area: backend, priority: 2 - normal, type: bug

#964 Filtering: Implement bad words detection in nicknames
  bot/cogs/filtering.py
  bot/utils/redis_cache.py
  tests/bot/utils/test_redis_cache.py
Labels: area: moderation, priority: 2 - normal, type: feature

#997 Escape markdown in charinfo embed
  bot/cogs/utils.py
Labels: area: frontend, priority: 3 - low, type: bug

#978 Use Scheduler instead of asyncio.sleep on silence cog
  bot/cogs/moderation/silence.py
  tests/bot/cogs/moderation/test_silence.py
Labels: a: moderation, p: 2 - normal, t: bug

#937 Make token detection more robust and completely rewrite its tests
  bot/cogs/token_remover.py
  bot/utils/__init__.py
  tests/bot/cogs/test_token_remover.py
  tests/helpers.py
Labels: a: filters, p: 2 - normal, t: bug

#987 Add persistence to the help channel system
  bot/cogs/help_channels.py
  bot/utils/redis_cache.py
  tests/bot/utils/test_redis_cache.py
Labels: a: help channels, l: 1 - intermediate, p: 1 - high

#1001 Check infraction reason isn't None before shortening it
  bot/cogs/moderation/infractions.py
  bot/cogs/moderation/scheduler.py
Labels: a: moderation, p: 0 - critical, t: bug

#991 Create cooldown.md
  bot/resources/tags/customcooldown.md
Labels: a: information, p: 3 - low, t: feature

#892 #364 offensive msg autodeletion
  bot/cogs/filtering.py
  bot/constants.py
  config-default.yml
Labels: a: filters, p: 2 - normal, s: stalled, t: feature

#1003 Ignore DMs in token and webhook removers
  bot/cogs/token_remover.py
  bot/cogs/webhook_remover.py
  tests/bot/cogs/test_token_remover.py
Labels: a: filters, needs 1 approval, p: 3 - low, t: bug

#1015 Add Pipenv script for html coverage report
  Pipfile
Labels: a: dependencies, p: 3 - low, t: feature

#1009 Fix 400 when "clyde" is in any webhook username
  bot/cogs/duck_pond.py
  bot/cogs/python_news.py
  bot/cogs/reddit.py
  bot/cogs/watchchannels/watchchannel.py
  bot/utils/messages.py
  tests/bot/utils/test_messages.py
Labels: a: moderation, p: 3 - low, t: bug

#950 Created tests for startup logging
  tests/bot/cogs/test_logging.py
Labels: a: tests, p: 3 - low

#1002 Sync: ignore events from other guilds
  bot/cogs/sync/cog.py
  tests/bot/cogs/sync/test_cog.py
Labels: a: backend, p: 2 - normal, t: bug

#981 Improve LinePaginator to support long lines
  bot/cogs/help.py
  bot/cogs/moderation/management.py
  bot/cogs/watchchannels/talentpool.py
  bot/pagination.py
  tests/bot/test_pagination.py
Labels: a: utility, p: 2 - normal, t: bug
