Repository python-discord/bot, pull requests merged in 2021-03, with the labels that each got.

#1262 Defcon overhaul
  bot/constants.py
  bot/converters.py
  bot/exts/info/information.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/slowmode.py
  bot/utils/time.py
  config-default.yml
Labels: a: frontend, a: moderation, p: 1 - high, t: feature

#1434 Send command help for BadUnionArgument errors
  bot/exts/backend/error_handler.py
Labels: a: backend, p: 2 - normal, t: bug

#1392 Don't fuzzy search for tags when tag is on cooldown
  bot/exts/info/tags.py
Labels: a: backend, p: 2 - normal, t: bug

#1402 Implement showing filterlist entry comment in alerts
  bot/exts/filters/filtering.py
Labels: a: filters, p: 1 - high, t: feature

#1450 Only allow some characters within a request URL to PyPi.
  bot/exts/info/pypi.py
Labels: a: backend, p: 2 - normal, t: enhancement

#1445 Migrate talentpool to new API schema
  bot/exts/moderation/watchchannels/_watchchannel.py
  bot/exts/moderation/watchchannels/talentpool.py
Labels: a: API, a: moderation, p: 1 - high, t: enhancement

#1456 Revert "Use JSON logging in production"
  Pipfile
  Pipfile.lock
  bot/log.py
Labels: a: backend, a: information, p: 2 - normal

#1453 Purge ban now shows that user was purge banned within infraction message.
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/infractions.py
  tests/bot/exts/moderation/infraction/test_infractions.py
Labels: a: backend, p: 2 - normal, t: enhancement

#1460 Compose: read all env vars from '.env'
  docker-compose.yml
Labels: a: tools, p: 2 - normal, t: enhancement

#1452 Remove invoked command and message after failure.
  bot/exts/info/pypi.py
Labels: a: backend, p: 2 - normal, t: feature

#1455 Allow the sf command to take more than one snowflake at the time
  bot/exts/utils/utils.py
Labels: a: utility, p: 2 - normal, t: enhancement

#1461 Simplifying the PyPi command.
  bot/exts/info/pypi.py
Labels: a: backend, p: 2 - normal, t: enhancement

#1465 Use .gitattributes to normalise line endings on check-in
  .gitattributes
  .pre-commit-config.yaml
Labels: a: tools, p: 3 - low, t: enhancement

#1468 Account for defcon threshold being None when displaying server info
  bot/exts/info/information.py
  bot/exts/moderation/defcon.py
Labels: a: information, p: 3 - low, t: bug

#1467 Code block: remove null bytes before parsing AST
  bot/exts/info/codeblock/_parsing.py
Labels: a: information, p: 3 - low, t: bug

#1435 Instructions to dispute an infraction vary by infraction type.
  bot/exts/moderation/infraction/_utils.py
  tests/bot/exts/moderation/infraction/test_utils.py
Labels: a: backend, a: moderation, p: 2 - normal, t: enhancement

#1459 Talentpool Autoreview
  bot/exts/moderation/watchchannels/_watchchannel.py
  bot/exts/recruitment/__init__.py
  bot/exts/recruitment/talentpool/__init__.py
  bot/exts/recruitment/talentpool/_cog.py
  bot/exts/recruitment/talentpool/_review.py
  bot/utils/time.py
Labels: a: frontend, p: 1 - high, t: feature

#1466 feat: add new discord.py tags
  bot/resources/tags/customhelp.md
  bot/resources/tags/intents.md
Labels: a: tags, p: 3 - low, t: feature

#1486 !dmrelay command
  bot/exts/moderation/dm_relay.py
  bot/utils/services.py
  tests/bot/utils/test_services.py
Labels: a: moderation, a: utility, p: 1 - high, t: feature

#1488 Filter codeblock escapes and allow no mentions for !raw command
  bot/exts/info/information.py
Labels: a: backend, p: 2 - normal, t: enhancement

#1490 Increase the total number of help channels to 42
  config-default.yml
Labels: a: help channels, p: 2 - normal, t: enhancement

#1470 Extend close time logic to differentiate between the claimant and other users
  Pipfile
  Pipfile.lock
  bot/constants.py
  bot/exts/help_channels/_caches.py
  bot/exts/help_channels/_channel.py
  bot/exts/help_channels/_cog.py
  bot/exts/help_channels/_message.py
  bot/exts/help_channels/_stats.py
  config-default.yml
Labels: a: help channels, p: 1 - high, t: feature

#1491 Small fixes/improvements for `!dmrelay`
  bot/constants.py
  bot/exts/moderation/dm_relay.py
  config-default.yml
Labels: a: moderation, a: utility, p: 2 - normal, t: enhancement
