Repository python-discord/bot, pull requests merged in 2021-11, with the labels that each got.

#1901 Migrate to `og_blurple`
  bot/exts/backend/branding/_cog.py
  bot/exts/events/code_jams/_cog.py
  bot/exts/info/information.py
  bot/exts/info/site.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/infraction/management.py
  bot/exts/moderation/modlog.py
  bot/exts/utils/extensions.py
  bot/exts/utils/internal.py
  bot/exts/utils/reminders.py
  bot/exts/utils/utils.py
  tests/bot/exts/info/test_information.py
Labels: a: backend, p: 3 - low, s: waiting for author, t: enhancement

#1918 Add sql-fstring tag
  bot/resources/tags/sql-fstring.md
Labels: p: 3 - low, a: tags, t: enhancement, s: needs review

#1937 Improve Filter Rerun Logic
  bot/exts/filters/filtering.py
Labels: t: bug, a: filters, p: 2 - normal, s: needs review

#1942 commands: add pip as an alias to pypi
  bot/exts/info/pypi.py
Labels: a: backend, p: 3 - low, a: information, t: enhancement

#1926 Add support for `!infractions by <m|me|uid>`
  bot/exts/moderation/infraction/management.py
Labels: t: feature, a: backend, a: moderation, p: 3 - low, s: needs review

#1947 Fix `!infractions by me`
  bot/exts/moderation/infraction/management.py
Labels: t: bug, a: moderation, p: 2 - normal

#1950 Change log level from `WARNING` to `DEBUG`.
  bot/exts/help_channels/_cog.py
Labels: a: backend, p: 3 - low, t: enhancement

#1953 Add #bot-commands to guild features in !server
  bot/exts/info/information.py
Labels: a: frontend, p: 2 - normal, a: information, t: enhancement

#1446 Enhancing information within the incidents channel.
  bot/constants.py
  bot/exts/moderation/incidents.py
  config-default.yml
  tests/bot/exts/moderation/test_incidents.py
Labels: t: feature, a: backend, p: 2 - normal, s: needs review

#1966 Disable File Logging By Default
  bot/constants.py
  bot/log.py
  config-default.yml
  docker-compose.yml
Labels: a: frontend, p: 2 - normal, t: enhancement

#1959 Add ability to reply to message for `!remind`
  bot/exts/utils/reminders.py
Labels: p: 3 - low, a: utility, t: enhancement, s: needs review

#1971 Deal with activity_blocks not being returned by site
  bot/exts/info/information.py
  bot/exts/moderation/voice_gate.py
Labels: a: frontend, p: 2 - normal, t: enhancement, s: needs review

#1976 Added suppress for NotFound error
  bot/exts/moderation/clean.py
Labels: p: 2 - normal, a: utility, s: needs review

#1980 Limit the length of the invalid rule indices message
  bot/exts/info/site.py
Labels: t: bug, a: frontend

#1979 Use bright_green for "Currently Helping" DMs
  bot/exts/help_channels/_cog.py
Labels: a: frontend, p: 3 - low, t: enhancement, s: needs review

#1981 Small changes to invalid rule indices message shortening
  bot/exts/info/site.py
Labels: a: frontend, p: 3 - low, t: enhancement, s: needs review
