Repository python-discord/bot, pull requests merged in 2021-07, with the labels that each got.

#1669 Adds Documentation For Running A Single Test
  tests/README.md
Labels: a: docs, a: tests, p: 1 - high, t: enhancement

#1668 chore: Add the codejam create command
  bot/constants.py
  bot/exts/utils/jams.py
  config-default.yml
  tests/bot/exts/utils/test_jams.py
  tests/helpers.py
Labels: a: utility, p: 1 - high, t: feature

#1297 Implements Voice Channel Muting
  bot/constants.py
  bot/converters.py
  bot/exts/backend/error_handler.py
  bot/exts/moderation/silence.py
  config-default.yml
  tests/bot/exts/backend/test_error_handler.py
  tests/bot/exts/moderation/test_silence.py
  tests/bot/test_converters.py
  tests/helpers.py
Labels: a: moderation, p: 1 - high, t: feature

#1676 Drop GPL Dependencies
  bot/errors.py
  bot/exts/backend/error_handler.py
  bot/exts/info/help.py
  bot/exts/info/information.py
  bot/exts/moderation/infraction/_utils.py
  bot/exts/utils/ping.py
  bot/pagination.py
  poetry.lock
  pyproject.toml
  tests/bot/exts/backend/test_error_handler.py
  tests/bot/exts/info/test_help.py
Labels: a: dependencies, p: 1 - high, t: enhancement

#1666 Make use of the new Discord features
  bot/exts/backend/branding/_cog.py
  bot/exts/filters/antispam.py
  bot/exts/info/doc/_parsing.py
  bot/exts/info/information.py
  bot/exts/info/python_news.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/infraction/_utils.py
  bot/exts/moderation/infraction/management.py
  bot/exts/moderation/modlog.py
  bot/exts/moderation/stream.py
  bot/exts/moderation/watchchannels/_watchchannel.py
  bot/exts/recruitment/talentpool/_review.py
  bot/exts/utils/reminders.py
  bot/exts/utils/utils.py
  bot/pagination.py
  bot/utils/time.py
  tests/bot/exts/info/test_information.py
  tests/bot/exts/moderation/infraction/test_utils.py
  tests/bot/exts/moderation/test_modlog.py
  tests/bot/utils/test_time.py
Labels: a: frontend, p: 2 - normal, t: enhancement

#1687 Reminder: remove footer
  bot/exts/utils/reminders.py
Labels: a: utility, p: 3 - low, t: enhancement

#1686 Added docstring tag
  bot/resources/tags/docstring.md
Labels: a: backend, a: tags, good first issue, p: 3 - low, t: feature

#1694 Prevent ghost-pings in docs get command
  bot/exts/info/doc/_cog.py
Labels: a: frontend, a: utility, p: 3 - low, t: enhancement

#1696 Prevent ghost-pings in pypi command
  bot/exts/info/doc/_cog.py
  bot/exts/info/pypi.py
  bot/utils/messages.py
Labels: a: frontend, a: utility, p: 3 - low, t: enhancement
