Repository python-discord/bot, pull requests merged in 2022-05, with the labels that each got.

#2145 Make modpings rescheduling robust to unfilled cache
  bot/exts/moderation/modpings.py
Labels: t: bug, a: moderation, p: 2 - normal

#2173 Bump Bot Core to v7.0.0
  bot/exts/filters/filtering.py
  poetry.lock
  pyproject.toml
Labels: t: bug, a: moderation, p: 1 - high

#2163 Don't decode empty content as json in thread bumper
  bot/exts/utils/thread_bumper.py
Labels: t: bug, a: API, p: 2 - normal

#2161 Remove rediscache from thread bumper now it's been migrated
  bot/exts/utils/thread_bumper.py
Labels: a: backend, p: 3 - low, s: needs review

#2176 Catch correct exception in clean cog
  bot/exts/moderation/clean.py
Labels: t: bug, p: 2 - normal, s: needs review

#2156 revert bump to markdownify version, ensure redis cache ttl is set correctly
  bot/exts/info/doc/_cog.py
  bot/exts/info/doc/_redis_cache.py
  poetry.lock
  pyproject.toml
Labels: a: frontend, p: 1 - high, t: enhancement, status: approved, s: needs review

#2178 Fix !clean users command to handle more than one user
  bot/exts/moderation/clean.py
Labels: a: backend, a: moderation, p: 3 - low, t: enhancement, s: needs review

#2180 Log more data on failed clean
  bot/exts/backend/error_handler.py
  bot/exts/moderation/modlog.py
Labels: a: backend, a: moderation, p: 3 - low, t: enhancement, s: needs review

#2179 Updating and improving clarity in help documentation for clean subcommands
  bot/exts/moderation/clean.py
Labels: a: docs, p: 3 - low, s: waiting for author, t: enhancement
