Repository python-discord/bot, pull requests merged in 2022-09, with the labels that each got.

#2268 Use venvs with poetry in Dockerfile
  .github/workflows/lint-test.yml
  Dockerfile
Labels: t: bug, p: 0 - critical, a: tools, s: needs review

#2233 Allow referencing message as argument to `!remind edit content`
  bot/exts/utils/reminders.py
Labels: a: backend, p: 3 - low, a: utility, t: enhancement, s: needs review

#2272 Removed italics from the help command
  bot/exts/info/help.py
  bot/pagination.py
Labels: a: frontend, p: 2 - normal, t: enhancement, s: needs review

#2277 Use Python Poetry Base Action
  Dockerfile
Labels: a: dependencies, p: 1 - high, a: CI, t: enhancement

#2241 Disable nose plugin in pytest
  pyproject.toml
Labels: a: backend, p: 3 - low, a: tests, s: needs review

#2273 Fix error in help channels cog which assumed an embed would have a description
  bot/exts/help_channels/_channel.py
Labels: t: bug, p: 3 - low, a: help channels, s: needs review

#2242 Fix not awaited coroutine warning
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/infractions.py
  bot/exts/moderation/infraction/superstarify.py
  tests/bot/exts/moderation/infraction/test_infractions.py
Labels: a: backend, p: 3 - low, a: tests, s: needs review

#2259 feat: add reason argument to pardon commands
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/infractions.py
  tests/bot/exts/moderation/infraction/test_infractions.py
Labels: a: moderation, p: 1 - high, t: enhancement, s: needs review

#2265 Remove unnecessary error logging when cleanbanning a banned user
  bot/exts/moderation/infraction/infractions.py
Labels: t: bug, a: moderation, p: 2 - normal, s: needs review

#2232 Add ability to delete multiple reminders at once & display mentions in `!remind list`.
  bot/exts/utils/reminders.py
Labels: a: backend, p: 3 - low, a: utility, t: enhancement, s: needs review
