Repository python-discord/bot, pull requests merged in 2022-04, with the labels that each got.

#2117 Add Resources Command
  bot/exts/info/resources.py
  bot/resources/tags/resources.md
Labels: a: backend, p: 3 - low, t: enhancement, s: needs review

#2123 Update to canonical PEP URLs
  bot/exts/info/pep.py
  bot/exts/info/python_news.py
  bot/resources/tags/dictcomps.md
  bot/resources/tags/docstring.md
  bot/resources/tags/enumerate.md
  bot/resources/tags/indent.md
  bot/resources/tags/pathlib.md
  bot/resources/tags/pep8.md
  bot/resources/tags/positional-keyword.md
  bot/resources/tags/quotes.md
  bot/resources/tags/sql-fstring.md
  bot/resources/tags/star-imports.md
  bot/resources/tags/with.md
Labels: p: 3 - low, t: enhancement, s: needs review

#2069 Ping Moderators On Bad Words In Username, Also Checks For Bad Words When Joining Or Switching Voicechannels
  bot/exts/filters/filtering.py
Labels: a: backend, a: filters, p: 2 - normal, t: enhancement, s: needs review

#1943 Make type-hint tag
  bot/resources/tags/type-hint.md
Labels: a: backend, p: 3 - low, a: tags, s: needs review

#2140 wait_for event param is now positional only
  bot/exts/moderation/incidents.py
Labels: a: backend, p: 1 - high

#2137 Don't try to get modlog cog on defcon cog_load
  bot/exts/moderation/defcon.py
Labels: t: bug, a: backend, p: 0 - critical, s: needs review

#2138 Use the extensions list & util from bot-core
  .github/CODEOWNERS
  bot/converters.py
  bot/exts/utils/extensions.py
  bot/utils/extensions.py
  poetry.lock
  pyproject.toml
Labels: a: backend, p: 1 - high, s: needs review

#2143 Bump bot-core
  poetry.lock
  pyproject.toml
Labels: a: dependencies, p: 1 - high

#2133 Add discord.Thread to slowmode cog channel converters
  bot/exts/moderation/slowmode.py
Labels: t: feature, a: moderation, p: 2 - normal, s: needs review

#2146 Add support for BIG SOLIDUS unicode characters in off topic names
  bot/converters.py
Labels: a: frontend, a: moderation, p: 3 - low, t: enhancement

#2144 Make extension management async
  bot/exts/utils/extensions.py
Labels: t: bug, p: 1 - high, a: utility

#2148 Speed Up Sync Cog Loading
  bot/exts/backend/sync/_cog.py
  bot/exts/backend/sync/_syncers.py
  tests/helpers.py
Labels: t: bug, a: backend, a: API, p: 1 - high

#2129 Use site api over redis for thread bumping
  bot/exts/utils/thread_bumper.py
Labels: a: API, p: 2 - normal, t: enhancement, s: needs review
