Repository python-discord/bot, pull requests merged in 2023-03, with the labels that each got.

#2305 Store time of last vote in redis to prevent vote triggering early
  bot/exts/recruitment/talentpool/_review.py
  tests/bot/exts/recruitment/talentpool/test_review.py
Labels: a: backend, p: 2 - normal, t: enhancement, a: recruitment, s: needs review

#2408 Scaffold server config via a bootstrapping script
  .gitignore
  bot/constants.py
  bot/exts/backend/branding/_cog.py
  bot/exts/backend/config_verifier.py
  bot/exts/filters/antispam.py
  bot/exts/fun/duck_pond.py
  bot/exts/help_channels/_channel.py
  bot/exts/help_channels/_cog.py
  bot/exts/help_channels/_stats.py
  bot/exts/info/codeblock/_cog.py
  bot/exts/moderation/incidents.py
  bot/exts/moderation/watchchannels/_watchchannel.py
  bot/exts/moderation/watchchannels/bigbrother.py
  bot/exts/recruitment/talentpool/_review.py
  botstrap.py
  config-default.yml
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: p: 2 - normal, t: enhancement, s: needs review, review: needs devops

#2326 Support `eval` (snekbox) file system and attachment display
  bot/constants.py
  bot/exts/utils/snekbox/__init__.py
  bot/exts/utils/snekbox/_cog.py
  bot/exts/utils/snekbox/_eval.py
  bot/exts/utils/snekbox/_io.py
  tests/bot/exts/utils/snekbox/__init__.py
  tests/bot/exts/utils/snekbox/test_io.py
  tests/bot/exts/utils/snekbox/test_snekbox.py
Labels: a: backend, a: utility, s: needs review, area: features

#2372 Display jump url to message invoking an infraction in infraction log
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/_utils.py
  bot/exts/moderation/infraction/management.py
Labels: a: frontend, a: moderation, s: needs review

#2470 Fix typehint that broke duckpond channel blacklist
  bot/constants.py
Labels: t: bug, a: backend, s: needs review

#2487 Improve wording in botstrap error
  botstrap.py
Labels: a: frontend, p: 3 - low, s: needs review

#2432 Bump python version to 3 11
  .github/workflows/lint-test.yml
  Dockerfile
  poetry.lock
  pyproject.toml
  tests/_autospec.py
Labels: a: dependencies, a: CI, p: 2 - normal, t: enhancement

#2388 Add new inplace tag
  bot/resources/tags/in-place.md
Labels: a: tags
