Repository python-discord/bot, pull requests merged in 2024-01, with the labels that each got.

#2856 Voice Verify Button Instead of Voice Verify Command
  .gitignore
  bot/constants.py
  bot/exts/moderation/voice_gate.py
Labels: a: frontend, a: moderation, p: 2 - normal, a: stats, s: needs review

#2880 Update unambiguous converter to not support usernames
  bot/converters.py
Labels: p: 3 - low, a: utility, s: needs review

#2877 Move modlog method to util
  bot/exts/moderation/clean.py
  bot/exts/moderation/defcon.py
  bot/exts/moderation/infraction/_scheduler.py
  bot/exts/moderation/infraction/management.py
  bot/exts/moderation/modlog.py
  bot/exts/moderation/watchchannels/_watchchannel.py
  bot/utils/modlog.py
  tests/bot/exts/moderation/test_modlog.py
Labels: p: 3 - low, a: utility, s: needs review

#2872 Fix pydantic warning in test due to deprecated function
  bot/exts/filtering/_utils.py
Labels: p: 3 - low, a: tests, t: enhancement, s: needs review

#2871 Fix test code that was doing nothing
  tests/bot/exts/backend/test_error_handler.py
Labels: t: bug, p: 3 - low, a: tests, s: needs review

#2580 Handle adding reactions to messages from users who have blocked the bot
  bot/bot.py
  bot/exts/backend/error_handler.py
Labels: t: bug, a: backend, p: 2 - normal

#2879 Use `LinePaginator` from `bot-core`
  bot/pagination.py
  poetry.lock
  pyproject.toml
  tests/bot/test_pagination.py
Labels: a: backend, s: stalled, p: 3 - low, t: enhancement
